# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific aliases and functions
PS1='\[\e[0;31m\]\u\[\e[m\] \[\e[1;34m\]\w\[\e[m\] $ '

export PERL5LIB=/vagrant/local/lib/perl5
export PATH=/vagrant/local/bin:$PATH
export MOJO_LISTEN="http://*:80"

cd /vagrant
