#!/bin/bash

USE_NYTPROF="$1"
if [[ -z $USE_NYTPROF ]]; then
    USE_NYTPROF=1
fi

perl -e 'warn "Devel::NYTProf is ", $ARGV[0] ? "enabled" : "disabled", "\n";' "$USE_NYTPROF"

sudo env USE_NYTPROF="$USE_NYTPROF" perl -i -pe 's/^\s*(PerlSetEnv\s+USE_NYTPROF\b).*$/$1 $ENV{USE_NYTPROF}/gmi' \
    /etc/httpd/conf.d/bugzilla.conf
sudo service httpd restart